import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {ROOT,loadData,slug,assetURL,publicPaper,paperVideos,hasVideo,missingAssets} from '../src/data.mjs';
import {esc,a,href,prose,markdown,layout,pageHeading,paperCard,topicCard,authorLine,paperLinks,tags,videoCard,jsonForHTML,sharedImage} from '../src/html.mjs';

export function build({quiet=false}={}){
 const d=loadData(), out=path.join(ROOT,'dist');
 // Validation runs before removing the previous successful build.
 fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(ROOT,'public'),out,{recursive:true});
 const routes=[];
 const write=(name,body)=>{const f=path.join(out,name.replace(/^\//,''));fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,body);};
 const page=(r,t,b,options={})=>{write(r,layout(d,r,t,b,options));routes.push(r);};
 const list=(ps,r,opts)=>ps.map(p=>paperCard(d,p,r,opts)).join('');
 const cv=r=>a(r,assetURL(d,d.site.cv_asset),'Curriculum vitae ↗','button secondary');
 const authorPeople=[...new Set(d.papers.flatMap(p=>p.authors).filter(n=>n!==d.site.name))].sort((a,b)=>a.localeCompare(b));
 const paperHead = p=>`<meta name="citation_title" content="${esc(p.title)}">${p.authors.map(n=>`<meta name="citation_author" content="${esc(n)}">`).join('')}${p.date?`<meta name="citation_publication_date" content="${esc(p.date.replaceAll('-','/'))}">`:''}${p.doi?`<meta name="citation_doi" content="${esc(p.doi)}">`:''}${p.pdf?`<meta name="citation_pdf_url" content="${esc(p.pdf.startsWith('/')?d.site.url+p.pdf:p.pdf)}">`:''}`;
 const now=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const upcoming=d.events.filter(e=>!e.draft&&e.end>=now).sort((a,b)=>a.start.localeCompare(b.start));
 // Home
 {
 const r='/index.html';
 const latestVideo=d.videos.find(v=>v.video);
 const body=`<section class="hero"><div class="hero-copy"><p class="eyebrow">Discrete geometry · Topological combinatorics</p><h1>Pablo<br>Soberón<span class="heading-dot">.</span></h1><p class="role">${esc(d.site.position)}<br>Baruch College & The Graduate Center, CUNY</p><p class="hero-intro">${esc(d.site.intro)}</p><div class="actions">${a(r,'/publications/','Explore publications →','button')}${cv(r)}</div><div class="social-links">${a(r,d.site.scholar,'Google Scholar ↗')}${a(r,d.site.orcid,'ORCID ↗')}${a(r,'mailto:'+d.site.email,'Email ↗')}</div></div><figure class="portrait">${sharedImage(r,d.site.portrait,d.site.name,{priority:true})}<figcaption>Mathematics in New York City</figcaption></figure></section>
 <section class="section symmetry-feature symmetry-image-only">
  <figure>${sharedImage(r,d.site.home_artwork.image,d.site.home_artwork.alt)}</figure>
</section>
 <section class="section"><div class="section-title"><div><p class="eyebrow">From the publication list</p><h2>Recent work</h2></div>${a(r,'/publications/','All publications →','text-link')}</div><div class="paper-list">${list(d.papers.slice(0,4),r,{compact:true})}</div></section>
 <section class="section"><div class="section-title"><div><p class="eyebrow">Questions & connections</p><h2>Research directions</h2></div>${a(r,'/research/','Research overview →','text-link')}</div><div class="topic-grid">${d.site.home_topics.map(id=>topicCard(d,d.topicMap[id],r)).join('')}</div></section>
 ${latestVideo?`<section class="section"><div class="section-title"><h2>Latest recording</h2>${a(r,'/videos/','Talks & videos →')}</div>${videoCard(d,latestVideo,r)}</section>`:''}
 <section class="section split-feature"><div><p class="eyebrow">Students & mentoring</p><h2>Starting in<br>discrete geometry.</h2><p>Research with undergraduates, the New York Discrete Mathematics REU, and notes for students beginning to explore combinatorial geometry.</p><div class="actions">${a(r,'/students/','Students & research →','button secondary')}${a(r,assetURL(d,'geometry-notes'),'Read the geometry notes (in progress) ↗','text-link')}</div></div><div class="local-math"><h3>Discrete geometry in NYC</h3><p>Information about the Baruch College discrete mathematics group, seminars, and our Research Experience for Undergraduates program.</p>${a(r,d.site.geometry_group,'Visit the group website ↗','text-link')}<div class="upcoming"${upcoming.length?'':' hidden'}><h3>Upcoming</h3>${upcoming.map(e=>`<article data-event-end="${esc(e.end)}"><p class="micro">${esc(e.start)} — ${esc(e.end)}</p><p>${a(r,e.url,e.title+' ↗')}</p><p class="muted">${esc(e.location)}</p></article>`).join('')}</div></div></section>`;
 page(r,'Home',body,{ld:{'@context':'https://schema.org','@type':'Person',name:d.site.name,url:d.site.url,jobTitle:d.site.position,affiliation:d.site.institutions.map(name=>({'@type':'Organization',name})),sameAs:[d.site.scholar,d.site.orcid]}});
 }
 // Research
 {
 const r='/research/index.html';
 page(r,'Research',pageHeading('Research','Geometry, combinatorics, topology.')+`<div class="prose intro-prose">${prose('research',r)}</div><div class="topic-grid all-topics">${d.topics.map(t=>topicCard(d,t,r)).join('')}</div><section class="section" id="selected"><div class="section-title"><div><p class="eyebrow">A curated selection</p><h2>Representative papers</h2></div>${a(r,'/publications/?view=featured','View in catalog →')}</div>${list(d.papers.filter(p=>p.featured),r)}</section>`,{section:'/research/'});
 for(const t of d.topics){const r=`/research/${t.id}/index.html`,ps=d.papers.filter(p=>p.topics.includes(t.id));page(r,t.title,`<p class="breadcrumb">${a(r,'/research/','Research')} / ${esc(t.title)}</p>`+pageHeading(`${ps.length} papers`,t.title,t.description)+`<div class="actions">${a(r,`/publications/?topic=${t.id}`,'Filter in publication catalog →','button secondary')}</div><div class="paper-list">${list(ps,r)}</div>${d.videos.some(v=>v.topics.includes(t.id)&&v.video)?`<section class="section"><h2>Related recordings</h2>${d.videos.filter(v=>v.topics.includes(t.id)&&v.video).map(v=>videoCard(d,v,r)).join('')}</section>`:''}`,{section:'/research/',description:t.description});}
 }
 // Publications: every result is real server-rendered HTML; JS only filters it.
 {
 const r='/publications/index.html',years=[...new Set(d.papers.map(p=>p.year))];
 const body=pageHeading('Research catalog','Publications','Browse by topic, year, coauthor, or type of work. A paper can appear in several lists.')+`<form class="filters" id="publication-filters" role="search"><label class="search-label">Search the catalog<input id="paper-search" name="q" type="search" placeholder="Title, coauthor, topic…" autocomplete="off"></label><div class="filter-row"><label>Topic<select name="topic" id="filter-topic"><option value="">All topics</option>${d.topics.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')}</select></label><label>Year<select name="year"><option value="">All years</option>${years.map(y=>`<option>${y}</option>`).join('')}</select></label><label>Status<select name="status"><option value="">All statuses</option>${['preprint','submitted','accepted','published'].map(s=>`<option value="${s}">${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select></label><label>Coauthor<select name="author"><option value="">All coauthors</option>${authorPeople.map(n=>`<option>${esc(n)}</option>`).join('')}</select></label></div><fieldset class="view-filters"><legend class="sr-only">Special lists</legend>${[['all','All papers'],['students','With students'],['video','With videos'],['survey','Surveys'],['featured','Selected']].map(([v,l])=>`<label><input type="radio" name="view" value="${v}"${v==='all'?' checked':''}><span>${l}</span></label>`).join('')}</fieldset><div class="filter-bottom"><p id="result-count" aria-live="polite">${d.papers.length} papers</p><button type="reset" class="reset">Clear filters</button></div></form><noscript><p class="notice">All papers are listed below. Filtering requires JavaScript; topic pages and paper links work without it.</p></noscript><p id="no-results" class="empty-state" hidden>No papers match these filters. Try another search or clear the filters.</p><div class="paper-list" id="paper-results">${list(d.papers,r,{filter:true})}</div>`;
 page(r,'Publications',body,{section:'/publications/'});
 }
 // Paper pages, BibTeX and Markdown. Author-only context appears only in data outputs.
 const bibtex=p=>{
   const clean=s=>String(s).replaceAll('\\','\\textbackslash{}').replace(/[{}]/g,m=>'\\'+m);
   const fields={title:'{'+clean(p.title)+'}',author:p.authors.map(clean).join(' and '),year:p.publication_year||p.year};
   if(p.arxiv){fields.eprint=p.arxiv;fields.archivePrefix='arXiv';fields.url='https://arxiv.org/abs/'+p.arxiv;}
   if(p.doi)fields.doi=p.doi;
   if(p.reference)fields.note=clean(p.reference);
   return `@misc{soberon-${p.year}-${p.id},\n${Object.entries(fields).map(([k,v])=>`  ${k} = {${v}}`).join(',\n')}\n}\n`;
 };
 const mdPaper=p=>{
   const v=publicPaper(d,p);
   return `# ${p.title}\n\nAuthors: ${p.authors.join('; ')}\nYear: ${p.year}\nStatus: ${p.status}\nPaper page: ${v.url}\n${p.reference?'Reference: '+p.reference+'\n':''}${p.arxiv?'arXiv: https://arxiv.org/abs/'+p.arxiv+'\n':''}${p.doi?'DOI: https://doi.org/'+p.doi+'\n':''}\nTopics: ${p.topics.map(t=>d.topicMap[t].title).join('; ')}\n${p.student_authors.length?'Student coauthors: '+p.student_authors.join('; ')+'\n':''}${p.notice?'\n## Author correction notice\n\n'+p.notice+'\nSource: '+p.notice_source+'\n':''}${p.abstract?'\n## Abstract\n\n'+p.abstract+'\n':''}${p.summary?'\n## Overview\n\n'+p.summary+'\n':''}${v.author_context?'\n## Author-written context\n\nAttribution: '+d.site.name+' (author). This is the author’s contextual assessment, not an independent evaluation.\n'+(v.author_context.updated?'Updated: '+v.author_context.updated+'\n':'')+'\n'+v.author_context.text+'\n':''}${v.videos.length?'\n## Videos\n\n'+v.videos.map(x=>`- [${x.title}](${x.url})`).join('\n')+'\n':''}`;
 };
 for(const p of d.papers){
 const r=`/papers/${p.id}/index.html`,vids=paperVideos(d,p),bib=bibtex(p),related=p.related_papers?.length?d.papers.filter(q=>p.related_papers.includes(q.id)):d.papers.filter(q=>q.id!==p.id&&q.topics.some(t=>p.topics.includes(t))).slice(0,3);
 const scholar={'@context':'https://schema.org','@type':'ScholarlyArticle','@id':d.site.url+`/papers/${p.id}/#article`,headline:p.title,name:p.title,author:p.authors.map(name=>({'@type':'Person',name})),url:d.site.url+`/papers/${p.id}/`,keywords:p.topics.map(t=>d.topicMap[t].title),...(p.abstract?{abstract:p.abstract}:{}),...(p.summary?{description:p.summary}:{}),...(p.date?{datePublished:p.date}:{}),...(p.doi?{identifier:p.doi}:{}),...(p.arxiv?{sameAs:'https://arxiv.org/abs/'+p.arxiv}:{})};
 const body=`<p class="breadcrumb">${a(r,'/publications/','Publications')} / ${p.year}</p><header class="paper-header"><p class="eyebrow">${p.year} · ${esc(p.status)}${p.type==='survey'?' · Survey':''}</p><h1>${esc(p.title)}</h1><p class="paper-authors">${p.authors.map(n=>n===d.site.name?esc(n):a(r,`/people/${slug(n)}/`,n)).join(', ')}</p>${p.reference?`<p class="reference">${esc(p.reference)}</p>`:''}<div class="paper-links large">${paperLinks(d,p,r)}</div>${tags(d,p,r)}</header>${p.notice?`<aside class="notice"><strong>Author correction notice</strong><p>${esc(p.notice)}</p>${a(r,p.notice_source,'Read the authors’ arXiv comments ↗')}</aside>`:''}<div class="paper-detail-grid"><div>${p.abstract?`<section class="prose"><h2>Abstract</h2>${markdown(p.abstract,r)}</section>`:p.summary?`<section class="prose"><h2>Overview</h2>${markdown(p.summary,r)}</section>`:`<div class="prose"><p>${p.arxiv?'The abstract and manuscript are available on '+a(r,'https://arxiv.org/abs/'+p.arxiv,'arXiv')+'.':p.pdf?'The manuscript is available as a '+a(r,p.pdf,'PDF')+'.':'Bibliographic information and resources for this paper.'}</p></div>`}${p.resources?.length?`<section class="section-small"><h2>Resources</h2><div class="resource-links">${p.resources.map(x=>a(r,x.url,x.label+' ↗')).join('')}</div></section>`:''}${p.student_authors.length?`<p class="student-note">With student ${p.student_authors.length===1?'coauthor':'coauthors'} ${p.student_authors.map(n=>a(r,`/people/${slug(n)}/`,n)).join(', ')}.</p>`:''}</div>${p.image?`<figure class="detail-figure"><img src="${href(r,p.image)}" alt="${esc(p.image_alt||'Illustration accompanying the paper')}" width="500" height="400"></figure>`:''}</div>${vids.length?`<section class="section" id="videos"><h2>Videos & talks</h2>${vids.map(v=>videoCard(d,v,r)).join('')}</section>`:''}<section class="section citation"><details><summary>BibTeX citation</summary><p class="micro">A minimal citation using the imported metadata. Journal references are retained in the note field.</p><pre id="bibtex"><code>${esc(bib)}</code></pre><div class="actions"><button class="button secondary" data-copy="bibtex">Copy BibTeX</button>${a(r,`/papers/${p.id}/citation.bib`,'Download .bib','text-link')}<span class="copy-status" aria-live="polite"></span></div></details></section>${related.length?`<section class="section"><div class="section-title"><h2>Related papers</h2></div>${list(related,r,{compact:true})}</section>`:''}`;
 page(r,p.title,body,{section:'/publications/',description:p.summary||p.abstract?.slice(0,180)||`${p.title}. ${p.authors.join(', ')}. ${p.year}.`,ld:scholar,head:paperHead(p)+`<link rel="alternate" type="text/markdown" href="${href(r,`/papers/${p.id}/index.md`)}">`});write(`/papers/${p.id}/citation.bib`,bib);write(`/papers/${p.id}/index.md`,mdPaper(p));
 }
 // Students
 {
 const r='/students/index.html',ps=d.papers.filter(p=>p.student_authors.length);
 page(r,'Students & mentoring',pageHeading('Research together','Students & mentoring')+`<div class="intro-prose prose">${prose('students',r)}</div><div class="actions">${a(r,d.site.reu,'New York Discrete Mathematics REU ↗','button')}${a(r,'mailto:'+d.site.email,'Contact me','button secondary')}</div><aside class="notes-feature"><div><p class="eyebrow">A starting point</p><h2>Combinatorial Geometry<br>for Undergraduate Students</h2><p>Notes introducing geometric ideas and questions for students beginning research.</p>${a(r,assetURL(d,'geometry-notes'),'Read the notes (PDF) →','button secondary')}<p class="micro">${a(r,'/files/archive/combinatorial-geometry-local-copy.pdf','An older local copy (77 pages) is also available.')}</p></div><div class="notes-art"><img src="${href(r,d.topicMap.tverberg.image)}" alt="" width="300" height="250" loading="lazy"></div></aside><section class="section"><div class="section-title"><div><p class="eyebrow">Joint research</p><h2>Papers with students</h2></div>${a(r,'/publications/?view=students',`${ps.length} papers in the catalog →`)}</div><p class="muted">Student status refers to the collaboration on the paper, not the coauthor’s current position. Highlighted author names identify student collaborators.</p>${list(ps,r)}</section><section class="section"><h2>Competition mathematics</h2><p>Problem-solving resources and material used in olympiad training.</p><div class="actions">${a(r,'/teaching/putnam/','Putnam training →','button secondary')}${a(r,'/resources/spanish/','Materiales en español →','text-link')}</div></section>`,{section:'/students/'});
 }
 // Collaborator pages. No biographies or stale affiliations are inferred.
 {
 const r='/people/index.html';page(r,'Collaborators',pageHeading('Joint work','Collaborators','Coauthors and joint papers in this site’s publication catalog.')+`<div class="people-grid">${authorPeople.map(n=>{const ps=d.papers.filter(p=>p.authors.includes(n));return `<a class="person-link" href="${href(r,`/people/${slug(n)}/`)}"><strong>${esc(n)}</strong><span>${ps.length} joint ${ps.length===1?'paper':'papers'}${ps.some(p=>p.student_authors.includes(n))?' · Student collaboration':''}</span></a>`;}).join('')}</div>`,{});
 for(const n of authorPeople){const r=`/people/${slug(n)}/index.html`,ps=d.papers.filter(p=>p.authors.includes(n));page(r,n,`<p class="breadcrumb">${a(r,'/people/','Collaborators')}</p>`+pageHeading('Joint publications',n,`${ps.length} ${ps.length===1?'paper':'papers'} with Pablo Soberón in this catalog.`)+list(ps,r),{});}
 }
 // Teaching and an explicitly dated problem archive.
 {
 const r='/teaching/index.html';page(r,'Teaching',pageHeading('Courses & problem solving','Teaching')+`<div class="prose intro-prose">${prose('teaching',r)}</div><div class="actions">${a(r,d.site.brightspace,'CUNY Brightspace ↗','button')}</div><section class="section"><h2>Recent courses</h2><div class="course-list">${d.courses.map(c=>`<article><p class="small-label">${esc(c.term)}</p><h3>${esc(c.title)}</h3><p class="muted">${esc(c.code)} · Baruch College</p></article>`).join('')}</div></section><section class="section two-columns"><div><p class="eyebrow">Beyond a course</p><h2>Putnam training</h2><p>Nine problem sets, with available hints, from the 2017 problem-solving sessions.</p>${a(r,'/teaching/putnam/','Browse the problem sets →','button secondary')}</div><div><p class="eyebrow">Analysis</p><h2>The natural numbers</h2><p>Supplementary notes on a construction of the natural numbers.</p>${a(r,assetURL(d,'analysis-supplement'),'Read the supplement (PDF) ↗','button secondary')}</div></section>`,{section:'/teaching/'});
 const t='/teaching/putnam/index.html',topics=['General problems','Polynomials','Number theory','Combinatorics','Analysis','Inequalities','Extremal principle','Linear algebra','Functional equations'];
 page(t,'Putnam resources',`<p class="breadcrumb">${a(t,'/teaching/','Teaching')}</p>`+pageHeading('Problem-solving archive · 2017','Putnam training','Problem sets and available hints from the original website.')+`<div class="resource-list">${topics.map((label,i)=>`<article><div><p class="small-label">Set ${i+1}</p><h2>${esc(label)}</h2></div><div class="paper-links">${a(t,assetURL(d,`putnam-${i+1}`),'Problems (PDF) ↗')}${i<8?a(t,assetURL(d,`putnam-${i+1}-hints`),'Hints (PDF) ↗'):''}</div></article>`).join('')}</div>`,{section:'/teaching/'});
 }
 // Talks
 {const r='/videos/index.html';page(r,'Talks & videos',pageHeading('Explanations & lectures','Talks & videos','Recordings, paper explanations, and slides.')+`<div class="talk-list">${d.videos.map(v=>videoCard(d,v,r)).join('')}</div>${d.videos.some(v=>v.video)?'':`<p class="muted">This archive currently contains talk listings and available slides. Paper explanations will be added here as they are recorded.</p>`}`,{section:'/videos/'});}
 // Resources and notes
 {
 const r='/resources/index.html';page(r,'Books & resources',pageHeading('For readers & students','Books & resources')+`<div class="prose intro-prose">${prose('resources',r)}</div><div class="book-grid">${d.books.map(b=>`<article class="book"><img src="${href(r,b.image)}" alt="Cover of ${esc(b.title)}" width="210" height="300" loading="lazy"><div><p class="small-label">${b.year} · ${esc(b.language)}</p><h2>${esc(b.title)}</h2><p class="muted">${esc(b.subtitle)}<br>${esc(b.publisher)}</p><p>${esc(b.description)}</p>${a(r,b.url,'Publisher / book information ↗','text-link')}</div></article>`).join('')}</div><section class="section"><h2>Expository writing</h2><div class="resource-list"><article><div><h3>Gerrymandering, Sandwiches, and Topology</h3><p class="muted">Notices of the AMS 64(9), 1010–1013 (2017).</p></div>${a(r,'https://www.ams.org/publications/journals/notices/201709/rnoti-p1010.pdf','Article (PDF) ↗')}</article><article><div><h3>El principio de las casillas</h3><p class="muted">Tzaloa 2010(2), 1–6. In Spanish.</p></div>${a(r,'https://www.ommenlinea.org/wp-content/uploads/2014/01/10-2.pdf','Article (PDF) ↗')}</article></div></section><section class="section resource-grid"><a href="${href(r,'/resources/spanish/')}"><h2>Notas en español →</h2><p>Distribuciones justas y entrenamiento olímpico.</p></a><a href="${href(r,'/resources/reading/')}"><h2>Recommended reading →</h2><p>Books and papers across combinatorics and geometry.</p></a>${d.site.notes_enabled?`<a href="${href(r,'/notes/')}"><h2>Research notes →</h2><p>Exploratory and expository material, separate from the publication list.</p></a>`:''}</section>`,{});
 const s='/resources/spanish/index.html';page(s,'Notas en español',`<p class="breadcrumb">${a(s,'/resources/','Resources')}</p>`+pageHeading('Materiales de estudio','Notas en español')+`<div lang="es"><section><h2>Distribuciones justas</h2><p>Notas sobre problemas de distribución justa.</p>${a(s,assetURL(d,'fair-division-es'),'Descargar las notas (PDF) ↗','button secondary')}</section><section class="section"><h2>Entrenamiento olímpico · Panamá, 2020</h2><div class="resource-list">${['Avanzados — lista 1','Avanzados — lista 2','Iniciales — lista 1'].map((t,i)=>`<article><h3>${esc(t)}</h3>${a(s,assetURL(d,`panama-${i+1}`),'Problemas (PDF) ↗')}</article>`).join('')}</div></section></div>`,{});
 const b='/resources/reading/index.html';page(b,'Recommended reading',`<p class="breadcrumb">${a(b,'/resources/','Resources')}</p>`+pageHeading('Books & papers','Recommended reading','A selection from the reading list on the original site.')+`<div class="reading-list">${d.reading.map(x=>`<article><p class="small-label">${esc(x.authors)}</p><h2>${esc(x.title)}</h2><p>${esc(x.description)}</p>${x.url?a(b,x.url,'Read / find a copy ↗'):''}</article>`).join('')}</div>`,{});
 if(d.site.notes_enabled){const n='/notes/index.html';page(n,'Research notes',pageHeading('Exploration & exposition','Research notes','Notes are listed separately from research publications. Each note describes its scope and status.')+(!d.notes.length?'<p class="empty-state">No research notes have been posted here yet.</p>':d.notes.map(v=>`<article class="talk"><p class="small-label">${esc(v.date)} · ${esc(v.kind||'Exploratory note')}</p><h2>${a(n,`/notes/${v.id}/`,v.title)}</h2><p>${esc(v.summary||'')}</p></article>`).join('')),{});
 for(const v of d.notes){const r=`/notes/${v.id}/index.html`;page(r,v.title,`<p class="breadcrumb">${a(r,'/notes/','Research notes')}</p>`+pageHeading(v.kind||'Exploratory note',v.title)+`<p class="muted">${esc(v.date)}</p>${v.disclaimer?`<aside class="notice">${esc(v.disclaimer)}</aside>`:''}<div class="prose">${markdown(v.body||'',r)}</div>${v.pdf?a(r,v.pdf,'Read note (PDF) →','button'):''}`,{});}}
 }
 // About: personal material restored from the original site, kept as editable content.
 {
 const r='/about/index.html',about=d.about,sculpture=about.soberonita;
 const body=`<div class="surface about-intro">${pageHeading('Biography & contact','About me')}<div class="about-grid"><div><div class="prose">${prose('about',r)}</div><div class="actions">${cv(r)}${a(r,assetURL(d,d.site.short_cv_asset),'Short CV ↗','text-link')}</div><div class="social-links">${a(r,d.site.scholar,'Google Scholar ↗')}${a(r,d.site.orcid,'ORCID ↗')}</div></div>${sharedImage(r,d.site.portrait,d.site.name,{className:'about-portrait',priority:true})}</div></div>
 <section class="section institutions-section" aria-labelledby="institutions-heading"><p class="eyebrow">Places & people</p><h2 id="institutions-heading">Institutions close to my heart</h2><div class="institution-grid">${about.institutions.map(x=>`<article><h3>${esc(x.name)}</h3><p>${esc(x.location)}</p></article>`).join('')}</div><div class="education-section"><h2>Education</h2><div class="education-grid">${about.education.map(x=>`<article><div class="education-logo">${sharedImage(r,x.logo,x.institution+' logo')}</div><div><p class="small-label">${esc(x.dates)}</p><h3>${esc(x.institution)}</h3><p>${esc(x.qualification)}</p><p class="muted">${esc(x.advisors)}</p></div></article>`).join('')}</div></div></section>
 <section class="section sculpture-feature" aria-labelledby="sculpture-heading"><figure>${sharedImage(r,sculpture.image,sculpture.alt)}</figure><div><h2 id="sculpture-heading">${esc(sculpture.title)}</h2><p>${esc(sculpture.description)}</p></div></section>
 <section class="section quote-section" aria-label="Quotation from David Hilbert"><blockquote><p>“${esc(about.quote.text)}”</p><footer>${esc(about.quote.author)} · ${esc(about.quote.year)}</footer></blockquote></section>
 <section class="section two-columns"><div><p class="eyebrow">Contact</p><h2>Email</h2><p>${a(r,'mailto:'+d.site.email,d.site.email)}</p></div><div><p class="eyebrow">Baruch College</p><h2>Office</h2><address>${d.site.office.map(esc).join('<br>')}</address><p class="micro">${esc(d.site.mail_note)}</p></div></section>`;
 page(r,'About & contact',body,{section:'/about/'});
 }
 // Machine-readable corpus: public, author-attributed, NOT cloaked or user-agent-gated.
 write('/data/papers.json',JSON.stringify({schema_version:'1.0',site:d.site.url,author_context_policy:'Optional context is written by the author, not an independent evaluation. These public records are equally accessible to people and automated clients.',papers:d.papers.map(p=>publicPaper(d,p))},null,2)+'\n');
 write('/data/papers.md',`# Papers — ${d.site.name}\n\nAuthor-written context, when present, is attributed in each entry. It is not an independent assessment.\n\n`+d.papers.map(mdPaper).join('\n---\n\n'));
 write('/data/publications.bib',d.papers.map(bibtex).join('\n'));
 write('/llms.txt',`# ${d.site.name}\n\n> Academic website: discrete geometry and topological combinatorics.\n\n## Publications\n- [Paper catalog](${d.site.url}/data/papers.md): Bibliography, abstracts when available, and explicitly attributed author-written context.\n- [JSON catalog](${d.site.url}/data/papers.json): Structured equivalent of the same public data.\n- [Publications](${d.site.url}/publications/): Human-facing catalog and filters.\n- [BibTeX](${d.site.url}/data/publications.bib): Minimal imported citation records.\n\n## Other material\n- [Research](${d.site.url}/research/)\n- [Students](${d.site.url}/students/)\n- [Videos and talks](${d.site.url}/videos/)\n- [Exploratory notes](${d.site.url}/notes/): Separate from formal publications.\n\nEach paper page also has an index.md representation. Author-written context is the author’s assessment, not a publisher’s statement or an independent evaluation.\n`);
 {const r='/data/index.html';page(r,'Machine-readable catalog',pageHeading('Open representations','Machine-readable catalog','The same public research catalog, in formats suited to reuse.')+`<div class="prose"><p>These resources are available to everyone, not only to crawlers. Where a record contains additional author-written context, it is labeled as the author’s assessment rather than an independent evaluation. Such context is not displayed on the normal paper page.</p><p>The catalog is not a guarantee of indexing or use by any search engine or AI system.</p></div><div class="resource-list">${[['/data/papers.json','Publication catalog · JSON'],['/data/papers.md','Publication catalog · Markdown'],['/data/publications.bib','Publication catalog · BibTeX'],['/llms.txt','Site index for automated readers']].map(([url,t])=>`<article><h2>${esc(t)}</h2>${a(r,url,'Open →')}</article>`).join('')}</div>`,{});}
 // Feed dates: never invent day/month for undated historical bibliography.
 const feedPapers=d.papers.filter(p=>p.date).sort((a,b)=>b.date.localeCompare(a.date));
 write('/feed.xml',`<?xml version="1.0" encoding="utf-8"?><feed xmlns="http://www.w3.org/2005/Atom"><title>${esc(d.site.name)} — papers</title><id>${esc(d.site.url)}/</id><link href="${esc(d.site.url)}/feed.xml" rel="self"/><link href="${esc(d.site.url)}/"/><updated>${feedPapers[0]?.date||now}T12:00:00Z</updated><author><name>${esc(d.site.name)}</name></author>${feedPapers.map(p=>`<entry><id>${esc(d.site.url)}/papers/${p.id}/</id><title>${esc(p.title)}</title><link href="${esc(d.site.url)}/papers/${p.id}/"/><updated>${p.date}T12:00:00Z</updated><summary>${esc(p.summary||p.abstract||p.title)}</summary></entry>`).join('')}</feed>`);
 // Legacy URLs: HTTP redirects on Cloudflare + portable HTML fallbacks elsewhere.
 const redirects={'/full-list':'/publications/','/cv-about-me':'/about/','/student-activities':'/students/','/collaborators':'/people/','/more':'/videos/','/slides-seminars':'/videos/','/other-publications':'/resources/','/esp':'/resources/spanish/','/must-read':'/resources/reading/','/putnam-resources':'/teaching/putnam/','/tverberg-type-theorems':'/research/tverberg/','/tverberg-type-results':'/research/tverberg/','/mass-partitions':'/research/mass-partitions/','/helly-type-results':'/research/helly/','/graph-theory':'/research/graph-theory/','/surveys':'/publications/?view=survey','/copy-of-graph-theory':'/publications/'};
 let rules='';
 for(const [old,dest] of Object.entries(redirects)){rules+=`${old} ${dest} 301\n${old}/ ${dest} 301\n`;const r=old+'/index.html';write(r,`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Page moved</title><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url=${href(r,dest)}"><link rel="canonical" href="${esc(d.site.url+dest)}"></head><body><p>This page has moved. ${a(r,dest,'Continue to the new page →')}</p></body></html>`);}
 for(const x of d.assets)if(fs.existsSync(path.join(ROOT,x.destination))){const dest='/'+x.destination.replace(/^public\//,'');rules+=`${x.original_path} ${dest} 301\n`;const f=path.join(out,x.original_path);fs.mkdirSync(path.dirname(f),{recursive:true});fs.copyFileSync(path.join(ROOT,x.destination),f);}
 write('/_redirects',rules);
 write('/_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: SAMEORIGIN\n${d.site.preview_noindex?'  X-Robots-Tag: noindex, nofollow\n':''}`);
 write('/robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${d.site.url}/sitemap.xml\n`);
 write('/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${esc(d.site.url+r.replace(/index\.html$/,''))}</loc></url>`).join('')}</urlset>`);
 page('/404.html','Page not found',pageHeading('404','This page is not here.')+`<p>The address may have changed during the move from Wix.</p><div class="actions">${a('/404.html','/','Home →','button')}${a('/404.html','/publications/','Search publications →','button secondary')}</div>`,{});
 write('/.nojekyll','');
 fs.writeFileSync(path.join(ROOT,'tools/editor-data.js'),'window.SITE_EDITOR_DATA = '+jsonForHTML({papers:d.allPapers.map(({_file,...p})=>p),videos:d.allVideos.map(({_file,...v})=>v),topics:d.topics.map(({id,title})=>({id,title})),notes:d.allNotes.map(({_file,...v})=>v)})+';\n');
 fs.writeFileSync(path.join(ROOT,'migration/build-report.json'),JSON.stringify({built_at:new Date().toISOString(),papers:d.papers.length,student_papers:d.papers.filter(p=>p.student_authors.length).length,topics:d.topics.length,coauthors:authorPeople.length,pages:routes.length,missing_wix_documents:missingAssets(d).map(x=>({id:x.id,destination:x.destination,url:x.url})),preview_noindex:d.site.preview_noindex},null,2)+'\n');
 if(!quiet)console.log(`Built ${routes.length} pages: ${d.papers.length} papers, ${d.topics.length} topics, ${authorPeople.length} coauthors.\nOutput: dist/\n${missingAssets(d).length} Wix-only documents still need local copies. Run npm run import:wix before moving the domain.\nIndexing: ${d.site.preview_noindex?'OFF (preview)':'ON'}.`);
 return {routes,d,out};
}
if(process.argv[1] && import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){try{build();}catch(e){console.error(e.message);process.exitCode=1;}}
