'use strict';
const D=window.SITE_EDITOR_DATA, form=document.querySelector('#editor-form'),raw=document.querySelector('#raw-json'),status=document.querySelector('#status'),collection=document.querySelector('#collection'),choose=document.querySelector('#record');
let current={};
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10),year=()=>new Date().getFullYear();
const templates={papers:()=>({id:'new-paper',title:'',authors:['Pablo Soberón'],year:year(),date:today(),sort_order:0,status:'preprint',reference:'',type:'research',topics:[],student_authors:[],featured:false,arxiv:'',doi:'',pdf:'',summary:'',abstract:'',image:'',image_alt:'',resources:[],related_papers:[],agent_note:{attribution:'author',text:'',updated:''},methods:[],related_problems:[],draft:true}),videos:()=>({id:'new-video',title:'',kind:'paper-explainer',year:year(),date:today(),event:'',papers:[],topics:[],video:{type:'youtube',id:''},slides:'',description:'',draft:true}),notes:()=>({id:'new-note',title:'',date:today(),kind:'Exploratory note',topics:[],summary:'',body:'',pdf:'',disclaimer:'',draft:true})};
function field(label,key,value,{area=false,type='text',help='',full=false}={}){return `<label${full?' class="full"':''}>${h(label)}${area?`<textarea data-key="${key}" rows="${key==='abstract'||key==='agent_text'||key==='body'?6:3}">${h(value)}</textarea>`:`<input data-key="${key}" type="${type}" value="${h(value)}">`}${help?`<span class="help">${h(help)}</span>`:''}</label>`;}
function select(label,key,value,options){return `<label>${h(label)}<select data-key="${key}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${h(v)}"${v===value?' selected':''}>${h(t)}</option>`;}).join('')}</select></label>`;}
function checks(legend,key,options,selected=[]){return `<fieldset><legend>${h(legend)}</legend><div class="check-grid">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<label><input type="checkbox" data-array="${key}" value="${h(v)}"${selected.includes(v)?' checked':''}>${h(t)}</label>`;}).join('')}</div></fieldset>`;}
const check=(key,label,value)=>`<label class="checkline"><input type="checkbox" data-key="${key}"${value?' checked':''}>${h(label)}</label>`;
function render(){
 const p=current,mode=collection.value;
 let html=`<h2>${mode==='papers'?'Paper':mode==='videos'?'Talk or video':'Research note'} details</h2><div class="grid">${field('Stable ID / filename','id',p.id,{help:'Lowercase words joined by hyphens. Do not change an existing ID after publication.'})}${field('Title','title',p.title)}`;
 if(mode==='papers')html+=`${field('Year','year',p.year,{type:'number'})}${field('Date (optional)','date',p.date,{type:'date',help:'Used for RSS. Use the actual date, not an invented January 1.'})}${select('Status','status',p.status,['preprint','submitted','accepted','published'])}${select('Type','type',p.type,['research','survey'])}${field('Authors — one name per line','authors',p.authors.join('\n'),{area:true,help:'Use consistent full names. Student coauthors are chosen below.'})}${field('Journal reference','reference',p.reference,{area:true})}${field('arXiv ID','arxiv',p.arxiv,{help:'For example 2609.37876, without https://arxiv.org/abs/'})}${field('DOI','doi',p.doi,{help:'For example 10.1234/example, without https://doi.org/'})}${field('PDF path or URL','pdf',p.pdf,{help:'A local file: /files/papers/my-paper.pdf; or a full HTTPS URL.'})}${field('Illustration path','image',p.image,{help:'Optional. For example /images/my-figure.webp.'})}${field('Illustration alt text','image_alt',p.image_alt)}${field('Visible short overview','summary',p.summary,{area:true,full:true})}${field('Visible abstract','abstract',p.abstract,{area:true,full:true})}</div><div id="student-choices">${checks('Student coauthors on this paper','student_authors',p.authors,p.student_authors)}</div>${checks('Topics','topics',D.topics.map(t=>[t.id,t.title]),p.topics)}<div class="grid">${check('featured','Include among selected / representative papers',p.featured)}${check('draft','Draft — exclude from website and feeds',p.draft)}</div><h2>Author-written context for machines</h2><p class="help">Public in JSON and Markdown, but not shown on the normal paper page. Attributed to the author; do not put private notes here. This field does not promise search-engine visibility.</p><div class="grid">${field('Context / contribution / significance','agent_text',p.agent_note?.text||'',{area:true,full:true})}${field('Context last updated','agent_updated',p.agent_note?.updated||'',{type:'date'})}${field('Methods — one per line','methods',(p.methods||[]).join('\n'),{area:true})}${field('Related problems — one per line','related_problems',(p.related_problems||[]).join('\n'),{area:true})}</div>`;
 else if(mode==='videos')html+=`${field('Year','year',p.year,{type:'number'})}${field('Date','date',p.date,{type:'date'})}${select('Kind','kind',p.kind,['paper-explainer','talk'])}${field('Event / venue (optional)','event',p.event)}${select('Video source','video_type',p.video?.type||'none',[['none','No video — talk / slides only'],['youtube','YouTube'],['file','Direct video file'],['link','External recording link']])}${field('YouTube ID, YouTube URL, or file URL','video_url',p.video?.id||p.video?.url||'',{help:'YouTube: paste the watch/share URL or 11-character ID. Direct: /files/video.mp4 or an HTTPS URL.'})}${field('Poster image for direct video','video_poster',p.video?.poster||'')}${field('Slides URL / local path','slides',p.slides||'')}${field('Description','description',p.description,{area:true,full:true})}<label class="full">Associated papers — select one or more<select multiple data-key="papers">${D.papers.map(q=>`<option value="${h(q.id)}"${p.papers.includes(q.id)?' selected':''}>${h(q.title)}</option>`).join('')}</select><span class="help">Hold ⌘ (Mac) or Ctrl (Windows) to select several. Associations populate the paper pages automatically.</span></label></div>${checks('Topics','topics',D.topics.map(t=>[t.id,t.title]),p.topics)}${check('draft','Draft — exclude from website and feeds',p.draft)}<p class="help">Caption tracks and MIME type can be added using the complete JSON record below. Direct file playback is supported; large recordings should live outside the website repository.</p>`;
 else html+=`${field('Date','date',p.date,{type:'date'})}${field('Kind / label','kind',p.kind)}${field('Short summary','summary',p.summary,{area:true,full:true})}${field('Note body — simple Markdown','body',p.body,{area:true,full:true})}${field('PDF URL / local path','pdf',p.pdf)}${field('Scope or disclosure statement','disclaimer',p.disclaimer,{area:true,full:true,help:'For example, exploratory status, limitations, or an accurate description of AI assistance.'})}</div>${checks('Topics','topics',D.topics.map(t=>[t.id,t.title]),p.topics)}${check('draft','Draft — exclude from website and feeds',p.draft)}`;
 form.innerHTML=html;syncRaw();
}
function parseYouTube(s){s=s.trim();if(/^[A-Za-z0-9_-]{11}$/.test(s))return s;try{const u=new URL(s);if(['youtu.be','www.youtu.be'].includes(u.hostname))return u.pathname.split('/')[1];if(['www.youtube.com','youtube.com','m.youtube.com','www.youtube-nocookie.com'].includes(u.hostname))return u.searchParams.get('v')||u.pathname.split('/')[2]||s;}catch{}return s;}
function collect(){
 const mode=collection.value,p=current;
 for(const el of form.querySelectorAll('[data-key]')){const k=el.dataset.key;let v=el.type==='checkbox'?el.checked:el.multiple?[...el.selectedOptions].map(o=>o.value):el.value;
 if(['year','sort_order'].includes(k))v=Number(v);
 if(['authors','methods','related_problems'].includes(k))v=v.split('\n').map(s=>s.trim()).filter(Boolean);
 if(k.startsWith('agent_')){p.agent_note||={attribution:'author',text:'',updated:''};p.agent_note[k==='agent_text'?'text':'updated']=v;}
 else if(!k.startsWith('video_'))p[k]=v;
 }
 for(const key of ['topics','student_authors'])if(form.querySelector(`[data-array="${key}"]`))p[key]=[...form.querySelectorAll(`[data-array="${key}"]:checked`)].map(el=>el.value);
 if(mode==='videos'){
 const type=form.querySelector('[data-key=video_type]').value,url=form.querySelector('[data-key=video_url]').value.trim(),poster=form.querySelector('[data-key=video_poster]').value.trim(),old=p.video||{};
 p.video=type==='none'?null:type==='youtube'?{type,id:parseYouTube(url)}:{type,url,...(poster?{poster}:{}),...(old.captions?{captions:[]}:{}),...(old.captions?{captions:old.captions}:{}),...(old.mime?{mime:old.mime}:{})};
 }
 if(mode==='papers')p.student_authors=(p.student_authors||[]).filter(n=>p.authors.includes(n));
 syncRaw();
}
function syncRaw(){raw.value=JSON.stringify(current,null,2);document.querySelector('#destination').textContent=`Save to content/${collection.value}/${current.id||'new-record'}.json`;}
function menu(){choose.innerHTML='<option value="">— New record —</option>'+D[collection.value].map(p=>`<option value="${h(p.id)}">${h(p.title)}</option>`).join('');}
function setRecord(record){current=structuredClone(record);render();status.textContent='';status.classList.remove('error');}
function error(message){status.textContent=message;status.classList.add('error');}
collection.addEventListener('change',()=>{menu();setRecord(templates[collection.value]());});choose.addEventListener('change',()=>setRecord(D[collection.value].find(p=>p.id===choose.value)||templates[collection.value]()));document.querySelector('#new-record').addEventListener('click',()=>{choose.value='';setRecord(templates[collection.value]());});
form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',e=>{collect();if(e.target.dataset.key==='authors')document.querySelector('#student-choices').innerHTML=checks('Student coauthors on this paper','student_authors',current.authors,current.student_authors);});form.addEventListener('change',collect);
document.querySelector('#apply-json').addEventListener('click',()=>{try{const p=JSON.parse(raw.value);if(!p.id||typeof p.title!=='string')throw new Error('A record needs id and title.');setRecord({...templates[collection.value](),...p});status.textContent='JSON changes applied to the form.';}catch(e){error(e.message);}});
document.querySelector('#import-json').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const p=JSON.parse(await file.text());collection.value=p.authors?'papers':('video' in p||'papers' in p)?'videos':'notes';menu();choose.value=p.id;setRecord({...templates[collection.value](),...p});status.textContent='Imported '+file.name;}catch(e){error('Could not import JSON: '+e.message);}});
document.querySelector('#download').addEventListener('click',()=>{collect();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(current.id||''))return error('Use a lowercase hyphenated ID, such as my-paper.');if(!current.title?.trim())return error('Enter a title before downloading.');if(collection.value==='papers'&&!current.authors.length)return error('Enter at least one author.');if(collection.value==='videos'&&current.video?.type==='youtube'&&!/^[A-Za-z0-9_-]{11}$/.test(current.video.id))return error('Enter a valid 11-character YouTube ID or a YouTube watch/share URL.');const blob=new Blob([JSON.stringify(current,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status.classList.remove('error');status.textContent=`Downloaded ${current.id}.json. Move it to content/${collection.value}/, replacing the existing record when appropriate. Then run npm run check.`;});
menu();setRecord(templates.papers());
