import path from 'node:path';
import {localImage} from './images.mjs';
import fs from 'node:fs';
import {ROOT,slug,assetURL,hasVideo} from './data.mjs';
export const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const jsonForHTML = o => JSON.stringify(o).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
/** Relative index.html links support both a real web server and double-click preview. */
export function href(route,target){
  if(!target.startsWith('/')||target.startsWith('//'))return esc(target);
  const m=target.match(/^([^?#]*)(.*)$/),dest=m[1].endsWith('/')?m[1]+'index.html':m[1];
  let rel=path.posix.relative(path.posix.dirname(route),dest);if(!rel)rel=path.posix.basename(dest);
  return esc((rel.startsWith('.')?'':'./')+rel+m[2]);
}
export const a = (route,url,label,cls='') => `<a href="${href(route,url)}"${cls?` class="${esc(cls)}"`:''}>${esc(label)}</a>`;
export function markdown(text,route){
  // Small documented safe Markdown subset. Raw HTML is escaped, never executed.
  const inline=s=>esc(s).replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/[^\s)]*)\)/g,(_,label,url)=>`<a href="${href(route,url.replace(/&amp;/g,'&'))}">${label}</a>`).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*([^*]+)\*/g,'<em>$1</em>');
  return text.split(/\n\s*\n/).map(block=>{if(/^#{1,3} /.test(block)){const m=block.match(/^(#{1,3}) (.*)/s);return `<h${m[1].length}>${inline(m[2])}</h${m[1].length}>`;}if(/^```/.test(block))return `<pre><code>${esc(block.replace(/^```[^\n]*\n/,'').replace(/\n```$/,''))}</code></pre>`;if(/^- /.test(block))return `<ul>${block.split('\n').map(l=>`<li>${inline(l.replace(/^- /,''))}</li>`).join('')}</ul>`;return `<p>${inline(block).replace(/\n/g,' ')}</p>`;}).join('\n');
}
export function prose(name,route){const f=path.join(ROOT,'content/pages',name+'.md');return fs.existsSync(f)?markdown(fs.readFileSync(f,'utf8'),route):'';}
export function tags(d,p,route){return `<div class="tags">${(p.topics||[]).map(id=>a(route,`/research/${id}/`,d.topicMap[id].title,'tag')).join('')}${p.student_authors?.length?'<span class="tag quiet">With students</span>':''}${hasVideo(d,p)?a(route,`/papers/${p.id}/#videos`,'Video','tag'):''}</div>`;}
export const authorLine = p=>p.authors.map(n=>`<span${p.student_authors.includes(n)?' class="student-author" title="Student coauthor on this paper"':''}>${esc(n)}</span>`).join(', ');
export function paperLinks(d,p,route){return [p.arxiv?a(route,'https://arxiv.org/abs/'+p.arxiv,'arXiv ↗'):'',p.pdf?a(route,p.pdf,'PDF'):p.arxiv?a(route,'https://arxiv.org/pdf/'+p.arxiv,'PDF ↗'):'',p.doi?a(route,'https://doi.org/'+p.doi,'Journal ↗'):'',a(route,`/papers/${p.id}/citation.bib`,'BibTeX')].filter(Boolean).join('');}
export function paperCard(d,p,route,{compact=false,filter=false}={}){
  const search=JSON.stringify({title:p.title,authors:p.authors,topics:p.topics.map(t=>d.topicMap[t].title),year:p.year,reference:p.reference,summary:p.summary}).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  return `<article class="paper${compact?' compact':''}"${filter?` data-paper data-search="${esc(search)}" data-year="${p.year}" data-status="${p.status}" data-type="${p.type}" data-topics="${esc(p.topics.join(' '))}" data-students="${!!p.student_authors.length}" data-video="${hasVideo(d,p)}" data-featured="${!!p.featured}" data-authors="${esc(JSON.stringify(p.authors))}"`:''}><div class="paper-year">${p.year}</div><div class="paper-main"><div class="paper-eyebrow">${esc(p.status)}${p.type==='survey'?' · Survey':''}${p.notice?' · Author correction notice':''}</div><h${compact?'3':'2'}>${a(route,`/papers/${p.id}/`,p.title)}</h${compact?'3':'2'}><p class="authors">${authorLine(p)}</p>${p.reference?`<p class="reference">${esc(p.reference)}</p>`:''}${!compact&&p.summary?`<p class="paper-summary">${esc(p.summary)}</p>`:''}${!compact?tags(d,p,route):''}<div class="paper-links">${paperLinks(d,p,route)}${hasVideo(d,p)?a(route,`/papers/${p.id}/#videos`,'Watch explanation →'):''}</div></div>${p.image&&!compact?`<a class="paper-art" tabindex="-1" aria-hidden="true" href="${href(route,`/papers/${p.id}/`)}"><img src="${href(route,p.image)}" alt="" loading="lazy" width="156" height="126"></a>`:''}</article>`;
}
export function topicCard(d,t,route){return `<a class="topic-card" href="${href(route,`/research/${t.id}/`)}"><div class="topic-art">${t.image?`<img src="${href(route,t.image)}" alt="" loading="lazy" width="280" height="170">`:''}</div><div class="topic-copy"><h3>${esc(t.title)} <span aria-hidden="true">↗</span></h3><p>${esc(t.description)}</p><span class="small-label">${d.papers.filter(p=>p.topics.includes(t.id)).length} papers</span></div></a>`;}
export function videoEmbed(v,route){
 if(!v.video)return '';
 const x=v.video;
 if(x.type==='youtube')return `<div class="youtube-frame" data-youtube="${esc(x.id)}" data-title="${esc(v.title)}"><div><span class="play-symbol" aria-hidden="true">▶</span><p>Video on YouTube</p><button class="button" data-load-video>Load video</button><p class="micro">Loads YouTube only after you choose to play.</p><a href="https://www.youtube.com/watch?v=${esc(x.id)}">Watch on YouTube ↗</a></div></div>`;
 if(x.type==='link')return a(route,x.url,'Watch recording ↗','button');
 return `<video controls preload="metadata" playsinline${(x.captions||[]).some(c=>/^https?:/.test(c.url))?' crossorigin="anonymous"':''}${x.poster?` poster="${href(route,x.poster)}"`:''}><source src="${href(route,x.url)}" type="${esc(x.mime||(/\.webm(?:[?#]|$)/i.test(x.url)?'video/webm':'video/mp4'))}">${(x.captions||[]).map((c,i)=>`<track kind="captions" src="${href(route,c.url)}" srclang="${esc(c.language)}" label="${esc(c.label)}"${i===0?' default':''}>`).join('')}Your browser does not support this player. ${a(route,x.url,'Open the video file')}</video><p class="micro">${a(route,x.url,'Open video file ↗')}</p>`;
}
export function videoCard(d,v,route){return `<article class="talk" id="${esc(v.id)}"><div class="small-label">${v.year} · ${v.kind==='talk'?'Talk':'Paper explanation'}</div><h2>${esc(v.title)}</h2>${v.event?`<p class="muted">${esc(v.event)}${v.date?' · '+esc(v.date):''}</p>`:''}${v.description?`<div class="prose">${markdown(v.description,route)}</div>`:''}${videoEmbed(v,route)}<div class="paper-links">${v.slides_asset?a(route,assetURL(d,v.slides_asset),'Slides (PDF) ↗'):v.slides?a(route,v.slides,'Slides (PDF) ↗'):''}${v.papers.map(id=>a(route,`/papers/${id}/`,'Related paper →')).join('')}</div></article>`;}
export function sharedImage(route,url,alt,{className='',priority=false}={}) {
 const im=localImage(url);
 return `<img src="${href(route,im.url)}" alt="${esc(alt)}"${className?` class="${esc(className)}"`:''}${im.width&&im.height?` width="${im.width}" height="${im.height}"`:''}${priority?' fetchpriority="high"':' loading="lazy"'} decoding="async">`;
}
export function layout(d,route,title,body,{description='',section='',ld=null,head=''}={}){
 const canonical=d.site.url+route.replace(/index\.html$/,'');
 const nav=[['Research','/research/'],['Publications','/publications/'],['Students','/students/'],['Teaching','/teaching/'],['Talks & videos','/videos/'],['About','/about/']];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title==='Home'?d.site.name+' · '+d.site.tagline:title+' | '+d.site.name)}</title><meta name="description" content="${esc(description||d.site.description)}">${d.site.preview_noindex?'<meta name="robots" content="noindex, nofollow">':''}<link rel="canonical" href="${esc(canonical)}"><meta property="og:title" content="${esc(title==='Home'?d.site.name:title)}"><meta property="og:description" content="${esc(description||d.site.description)}"><meta property="og:type" content="website"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(d.site.url+localImage(d.site.portrait).url)}"><meta name="twitter:card" content="summary"><link rel="icon" href="${href(route,'/assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${href(route,'/assets/site.css')}"><link rel="alternate" type="application/atom+xml" href="${href(route,'/feed.xml')}" title="Pablo Soberón — new papers"><link rel="alternate" type="application/json" href="${href(route,'/data/papers.json')}" title="Publication catalog"><script src="${href(route,'/assets/site.js')}" defer></script>${ld?`<script type="application/ld+json">${jsonForHTML(ld)}</script>`:''}${head}</head><body><div class="site-backdrop" aria-hidden="true">${sharedImage(route,d.site.desktop_background,'')}</div><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="wordmark" href="${href(route,'/')}">Pablo Soberón<span>Academic website</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">☰</span></button><nav id="primary-nav" aria-label="Primary">${nav.map(([label,url])=>`<a href="${href(route,url)}"${section===url?' aria-current="page"':''}>${esc(label)}</a>`).join('')}</nav></div></header><main id="main" class="page${route==='/index.html'?' page-home':route==='/about/index.html'?' page-about':''}">${body}</main><footer class="site-footer"><div><a class="footer-name" href="${href(route,'/')}">Pablo Soberón</a><a href="mailto:${esc(d.site.email)}">${esc(d.site.email)}</a></div><nav aria-label="Footer">${a(route,'/resources/','Books & resources')}${a(route,'/people/','Collaborators')}${a(route,'/data/','Machine-readable catalog')}${a(route,'/feed.xml','RSS / Atom')}</nav><p class="copyright">© ${new Date().getUTCFullYear()} Pablo Soberón</p></footer></body></html>`;
}
export const pageHeading=(k,title,description='')=>`<div class="page-heading"><p class="eyebrow">${esc(k)}</p><h1>${esc(title)}</h1>${description?`<p class="lede">${esc(description)}</p>`:''}</div>`;
